services:
    typesense:
        image: typesense/typesense:28.0
        restart: on-failure
        volumes:
            - typesense-data:/data
        ports:
            - "8108:8108"
        command: '--data-dir /data --api-key=xyz --enable-cors'

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"

volumes:
    typesense-data:
        driver: local
    mysql_data:
        driver: local
